### ISSUE TITLE
Use XSound to process audio with neural network in real time?

### ISSUE THREAD

**Issue by indrasweb** [Korilakkuma/XSound#52]
Would it be possible to use XSound to process audio with a neural network in real time?

I would want to maintain a buffer of the last 1000ms of audio played by e.g. youtube, pipe this buffer through a neural network model using Onnx.js, then replace the youtube audio with this processed version. It would take about 30ms for the network to process the audio.

If you think it would be possible, any starting tips would be very much appreciated! Thanks :)

**Comment by Korilakkuma** [comment]
@indrasweb 

Currently, I don't know that it is possible to use XSound to process audio with a neural network in real time.

However,

> I would want to maintain a buffer of the last 1000ms of audio played

The latest version (greater than or equal to [v2.21.0](https://github.com/Korilakkuma/XSound/releases/tag/v2.21.0)) enables to slice `AudioBuffer`.
For example,

```JavaScript
const duration = X('audio').param('duration');
const startTime = duration - 1;  // sec
const buffer = X('audio').slice(startTime, duration);  // Sliced `AudioBuffer`

X('audio').ready(buffer).start(0);  // Set sliced `AudioBuffer` and Start audio
```

Thanks !
