### ISSUE TITLE
Connect to audio element

### ISSUE THREAD

**Issue by eetsceeck1** [Korilakkuma/XSound#90]
Hello, 
after messing some period with tuna.js i found this library which look much better, 
also there is a very weak support in tuna i left a question more than 2 weeks ago and still didn't got an answer, 

your library look better, and there is also "equalizer" in it, in a hope to implement it into my app i hope you can provide me any hint how to connect xsound to an audio element? such as i does with tuna? 

please take a look at my code:
```js
///	DEFINE AUDIO CONTEXT | (FOR PRIMARY AUDIO ELEMENT) | ON TIMEOUT.
	let audioContext = new AudioContext() || window.AudioContext || window.webkitAudioContext || window.mozAudioContext || window.msAudioContext; 

///	DEFINE AUDIO ELEMENT | PRIMARY AUDIO ELEMENT ("PlayBackAudioElement").
	let audio = document.getElementById("PlayBackAudioElement");

///	ANONYMOUS SOURCE CROSS ORIGIN.
	audio.crossOrigin = "anonymous";

/// DEFINE AUDIO SOURCE AS THE HTML AUDIO ELEMENT.
	let source = audioContext.createMediaElementSource(audio);

///	CREATE TUNA INSTANCE FOR ALL EFFECTS - CONECTED TO THE AUDIO CONTEXT.
var tuna = new Tuna(audioContext);

///	CREATE CONNECTION GAIN.
var TunaConnectionINPUT = audioContext.createGain();
var TunaConnectionOUTPUT = audioContext.createGain();

///	REVERB EFFECT.
var reverb = new tuna.Convolver({
    highCut: 19000,							//	20 to 22050
    lowCut: 200,                         	//	20 to 22050
    dryLevel: 0,                        	//	0 to 1+
    wetLevel: 0.5,							//	0 to 1+
    level: 1,                           	//	0 to 1+, TOTAL OUTPUT FOR WET AND DRY.
    impulse: "TunaAssets/impulse_rev.wav",	//	IMPULSE RESPONSE.
    bypass: 0
});

///	CONNECTION:
/// ****************************************************************************************
///	CONNECT REVERB INPUT TO THE REVERB EFFECT.
	TunaConnectionINPUT.connect(reverb);

///	CONNECT REVERB EFFECT TO THE REVERB OUTPUT (CREATED GAIN OUTPUT).
	reverb.connect(TunaConnectionOUTPUT);

///	CONNECT REVERB EFFECT THE AUDIO SOURCE.
	source.connect(reverb);

///	CONNECT REVERB EFFECT TO THE WEB AUDIO ELEMENT OUTPUT STREAM.
	reverb.connect(audioContext.destination);
/// ****************************************************************************************
```

i am trying to understand how should i connect xsound that way to my audio context?
thank you!

**Comment by Korilakkuma** [comment]
@bragle

Thank you for your nice question.
[`MediaElementAudioSourceNode` has cross-origin restrict](https://www.w3.org/TR/webaudio/#MediaElementAudioSourceOptions-security).
However, it is resolved to use Object URL that represents audio resource.

XSound can resolve it easily !

For example,

```ts
X('media').setup({
  media: document.querySelector('audio')
});

X.ajax({
  url: 'impulse_rev.wav',
  type: 'arraybuffer',
  successCallback: (event: ProgressEvent, arrayBuffer: ArrayBuffer) => {
    X.decode(X.get(), arrayBuffer, (rirAudioBuffer: AudioBuffer) => {
      // for Reverb
      X('media').module('reverb').preset({ rirs: [rirAudioBuffer] });
      X('media').module('reverb').param({
        buffer: 0,
        dry: 0.7,  // Sound Source Gain
        web: 0.3,  // Effect (Reverb) Gain
      }).activate();

      // for Equalizer
      X('media').module('equalizer').param({
        bass: 5,
        middle: - 3,
        treble: 5,
        presence: 2
      }).activate();

      X('media').start(X('media').param('currentTime'));
    }, () => {
       console.error('Decode error.');
    })
  },
  errorCallback: () => {
    console.error('The loading of RIR failed.');
  }
});
```

### API Document

  - `MediaModule` https://xsound.jp/docs/classes/main.MediaModule.html
  - `Equalizer` https://xsound.jp/docs/classes/main.Equalizer.html
  - `Reverb` https://xsound.jp/docs/classes/main.Reverb.html

### Playground

Select `MediaModule` and Click `Run` button https://xsound.jp/playground/

Thanks !

**Comment by eetsceeck1** [comment]
Hello tomohiro, thank you for your reply.

first i want to thank you for your support, 

i think i should explain little bit more about my app what is it so you will have a better understanding of what i am trying to achieve, if you will allow me please, 

the first thing first, i did set an example folder dedicated on your name on my server so you can check the app in live and understand what it does if you don't mind, 
you can reach it  here:
https://mrpro.cf:8000/Tomohiro/
please check my app in chrome / chromium only due to the API's codes some of them are not compatible with any other browser and actually are not meant to be, cause in the final project i will compile it into a web view based on chrome for cellphones devices, and for computer it will be reachable by a simple browser with CLI and OR with electron, so this project never meant to be compatible with firefox or safari,

also please check my app in dev mode on galaxy s9+ resolution so the "touch" codes will respond and also this app is still under development as you probably already understand it fits only this resolution at the moment (320x658),
=========================================================

this app is a media player, it can play radio stations, music, and video, 
i started this app for radio stations only, but i don't know how i found myself programming it into so many features during development, 

because it supposed to play radio stations as they are coming from different origins, so for the cross origin issue i needed to use proxy server which this app is using, so all requests are go through the proxy server, which is CORS anywhere, (a node.js proxy server).

so radio and music all goes through the proxy, 

the audio source is used for several things at once, first the same audio source is used for radio, 
and also the music, and also the file player, 
same audio source same audio element, 

the radio comes from an array, same as the music comes from the same array, 
they are all printed with php from mysql db, so i got one array with a list of radio stations and music, 

there is also a single file load and play feature which will unload the array and will load the file into the audio element once done 
the "ended" will unload this file and will bring back the array, 

please take a look at the next screenshot of my app before you might check it online:
![image](https://user-images.githubusercontent.com/43915916/191728082-fc03240b-ab34-4810-ad7d-d8f750e9a842.png)
the screenshot arrows represents the radio stations menu, music menu and the file player, 

please be aware they are all will play with the same audio element (PlayBackAudioElement) 
and the same source and audio context, 
"audio" and audioContext, 

i think in your example with decode it can play only a file what will be decoded first?

please bare in mind that i am not a professional javascript programmer, 
i am a very php programmer who struggling to do things in javascript, but i can find solutions just because programming languages are similar, and with a lot of help from the internet, 

so its not easy for me to understand your code without efforts, 
but now after 3 months programming in javascript more than 30000 lines of codes i have much better understanding in it, 

so please try to guide me if there is a way to connect it similarly or same as i have done with tuna after you got the whole picture of it, 

thank you thank you thank you for your support for your efforts!
i will wait for a reply
